# Generated by Django 3.1.6 on 2021-06-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='projectmanager',
            old_name='name',
            new_name='username',
        ),
    ]
