# Generated by Django 3.1.6 on 2021-06-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210626_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
