# Generated by Django 3.1.6 on 2021-06-28 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticket_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='developer',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_assigner', to=settings.AUTH_USER_MODEL),
        ),
    ]
