# Generated by Django 3.1.6 on 2021-06-28 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210628_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='creator',
        ),
        migrations.AddField(
            model_name='developer',
            name='asigner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_assigner', to=settings.AUTH_USER_MODEL),
        ),
    ]
