# Generated by Django 3.1.6 on 2021-06-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210628_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='asigner',
            new_name='assigner',
        ),
    ]
