# Generated by Django 3.1.6 on 2021-06-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210628_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_assigned',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_resolved',
            field=models.DateField(auto_now=True),
        ),
    ]
