# Generated by Django 3.1.6 on 2021-06-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210628_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ticket_image', models.ManyToManyField(to='core.Ticket')),
            ],
        ),
    ]
