# Generated by Django 3.1.6 on 2021-07-05 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_allimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allimage')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='AllImages',
        ),
        migrations.AddField(
            model_name='allimage',
            name='tickets',
            field=models.ManyToManyField(through='core.TicketImage', to='core.Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='allimages',
            field=models.ManyToManyField(through='core.TicketImage', to='core.AllImage'),
        ),
    ]
