# Generated by Django 3.1.6 on 2021-07-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210705_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allimage',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='allimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='allimage',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='allimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='allimages',
        ),
        migrations.AddField(
            model_name='allimage',
            name='ticket',
            field=models.ManyToManyField(to='core.Ticket'),
        ),
        migrations.DeleteModel(
            name='TicketImage',
        ),
    ]
