# Generated by Django 3.1.6 on 2021-07-07 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210706_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allimage',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.allimage'),
        ),
    ]
