# Generated by Django 3.1.6 on 2021-07-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210708_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allimage',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='img_ticket', to='core.ticket'),
        ),
    ]
