# Generated by Django 3.1.6 on 2021-07-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210710_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comment', to='core.comment'),
        ),
    ]
