# Generated by Django 3.1.6 on 2021-07-10 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210710_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allimage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_ticket', to='core.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_ticket', to='core.comment'),
        ),
    ]
