# Generated by Django 3.1.6 on 2021-07-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210712_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_assigner', to='core.administrator'),
        ),
    ]
