# Generated by Django 3.1.6 on 2021-08-08 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210720_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('begin_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('completion', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_creator', to='core.administrator')),
                ('project_lead', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_pm', to='core.projectmanager')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='Project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.project'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_project', to='core.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_project', to='core.project'),
        ),
    ]
