# Generated by Django 3.1.6 on 2021-08-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210808_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
