# Generated by Django 3.1.6 on 2021-08-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_projectstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Project',
            new_name='project',
        ),
    ]
