# Generated by Django 3.1.6 on 2021-08-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210808_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='begin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(),
        ),
    ]
